### ISSUE TITLE
特定ユーザーをフォローしようとするとエラーが出る

### ISSUE THREAD

**Issue by naaaaaaaaaaaf** [syuilo/dolphin#31]
### 内容
特定ユーザー( https://stellaria.network/@Eai )をリモートフォローしようとすると以下のエラーが出てフォローができません。

```
{
	"message": "Internal error occurred. Please contact us if the error persists.",
	"code": "INTERNAL_ERROR",
	"id": "5d37dbcb-891e-41ca-a3d6-e690c97775ac",
	"kind": "server",
	"info": {
		"e": {
			"message": "invalid person: invalid name",
			"code": "Error",
			"stack": "Error: invalid person: invalid name\n at validatePerson (/home/dolphin/dolphin/built/remote/activitypub/models/person.js:52:20)\n at Object.createPerson (/home/dolphin/dolphin/built/remote/activitypub/models/person.js:102:17)\n at runMicrotasks ()\n at processTicksAndRejections (internal/process/task_queues.js:93:5)\n at async fetchAny (/home/dolphin/dolphin/built/server/api/endpoints/ap/show.js:126:22)\n at async /home/dolphin/dolphin/built/server/api/endpoints/ap/show.js:37:20\n at async Object.exports.default (/home/dolphin/dolphin/built/server/api/call.js:36:12)"
		}
	}
}
```

### 環境
Dolphin v1.2.1

OS: Ubuntu 18.04
node.js v12.13.0
postgresql v11.5
redis v4.0.9

**Comment by syuilo** [comment]
名前が長すぎる可能性があります。
カスタム絵文字が含まれているようなので一見短そうですが文字列表記にした時に制限を超過していると思われます

**Comment by syuilo** [comment]
制限を緩和するか、わかりやすいエラーメッセージを表示するようにするかしたいと思います。
